/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.config;
import java.awt.Font;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC-001
 */
public class myorders extends javax.swing.JFrame {

    private String userId,id;
    
    /**
     * Creates new form myorders
     */
    public myorders() {
        initComponents();
        this.setLocationRelativeTo(null);
        displayData();
    }
    
    public myorders(String userId) {
        this.userId = userId;
        initComponents();
        this.setLocationRelativeTo(null);
        displayData();
    }

    myorders(int id) {
        this.userId = String.valueOf(id);
        initComponents();
        this.setLocationRelativeTo(null);
        displayData();
        
        // Add window listener to refresh data when window becomes visible
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                displayData();
            }
            
            @Override
            public void windowActivated(java.awt.event.WindowEvent e) {
                displayData();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PROFILE");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("HOME");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 20, 180, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MY ORDERS");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 190, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 160, 640));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product", "QTY", "Price", "Total", "Payment", "Order Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        // Column widths will be set in styleTable() method
        
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 730, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
// I-pasa ang 'this.id' aron ang Profile page makahibalo kinsang data ang i-load
    profile p = new profile(this.id); // I-pasa ang ID
    p.setVisible(true);
    this.dispose(); // Close ang dashboard
      
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(java.awt.Color.WHITE);
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      user_dashboard home = new user_dashboard(this.id); 
    home.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        jLabel12.setForeground(java.awt.Color.WHITE);
        jLabel12.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(java.awt.Color.WHITE);
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel6MouseExited
    
    private void displayData() {
        try {
            // Debug: Check if userId is available
            System.out.println("DEBUG: userId = " + this.userId);
            
            config con = new config();
            
            // Check if u_id column exists in tbl_sales, add it if it doesn't
            try {
                java.sql.Connection schemaConn = con.connectDB();
                java.sql.Statement schemaStmt = schemaConn.createStatement();
                schemaStmt.execute("ALTER TABLE tbl_sales ADD COLUMN u_id INTEGER DEFAULT 0");
                System.out.println("Added u_id column to tbl_sales");
            } catch (Exception e) {
                // Column probably already exists
                System.out.println("u_id column already exists or other error: " + e.getMessage());
            }
            
            // Check if userId is null or empty
            if (this.userId == null || this.userId.trim().isEmpty()) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                model.addRow(new Object[]{"Error: User ID not found", "", "", "", "", ""});
                styleTable();
                return;
            }
            
            // Get user info from tbl_accounts
            String userSql = "SELECT what_should_we_call_you FROM tbl_accounts WHERE u_id = ?";
            String customerName = "";
            
            try {
                java.sql.Connection userConn = con.connectDB();
                java.sql.PreparedStatement userPstmt = userConn.prepareStatement(userSql);
                userPstmt.setString(1, this.userId);
                java.sql.ResultSet userRs = userPstmt.executeQuery();
                
                if (userRs.next()) {
                    customerName = userRs.getString("what_should_we_call_you");
                    System.out.println("DEBUG: Customer name found: " + customerName);
                } else {
                    System.out.println("DEBUG: No customer found for ID: " + this.userId);
                }
                userRs.close();
            } catch (Exception e) {
                System.err.println("Error getting user data: " + e.getMessage());
            }
            
            if (customerName.isEmpty()) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                model.addRow(new Object[]{"User not found", "", "", "", ""});
                styleTable();
                return;
            }
            
            // Get user's orders from tbl_sales using u_id (more reliable than customer name)
            String ordersSql = "SELECT item_name, qty, price, total_amount, payment_method, sale_date " +
                           "FROM tbl_sales WHERE u_id = ? ORDER BY sale_date DESC";
            
            // DEBUG: Show all accounts in database
            System.out.println("=== DEBUG: ALL ACCOUNTS IN DATABASE ===");
            String debugAccountsSql = "SELECT u_id, what_should_we_call_you FROM tbl_accounts";
            try {
                java.sql.Connection debugConn2 = con.connectDB();
                java.sql.PreparedStatement debugPstmt2 = debugConn2.prepareStatement(debugAccountsSql);
                java.sql.ResultSet debugRs2 = debugPstmt2.executeQuery();
                
                while (debugRs2.next()) {
                    System.out.println("Account ID " + debugRs2.getInt("u_id") + 
                                     " - Name: '" + debugRs2.getString("what_should_we_call_you") + "'");
                }
                debugRs2.close();
            } catch (Exception e) {
                System.err.println("Debug accounts query error: " + e.getMessage());
            }
            System.out.println("=== END DEBUG ===");
            
            System.out.println("=== DEBUG: ALL SALES WITH USER IDS ===");
            String debugSalesSql = "SELECT u_id, customer_name, item_name, sale_date FROM tbl_sales ORDER BY sale_date DESC LIMIT 10";
            try {
                java.sql.Connection debugConn3 = con.connectDB();
                java.sql.PreparedStatement debugPstmt3 = debugConn3.prepareStatement(debugSalesSql);
                java.sql.ResultSet debugRs3 = debugPstmt3.executeQuery();
                
                while (debugRs3.next()) {
                    System.out.println("Sale - User ID: " + debugRs3.getInt("u_id") + 
                                     ", Customer: '" + debugRs3.getString("customer_name") + 
                                     "', Item: '" + debugRs3.getString("item_name") + 
                                     "', Date: " + debugRs3.getString("sale_date"));
                }
                debugRs3.close();
            } catch (Exception e) {
                System.err.println("Debug sales query error: " + e.getMessage());
            }
            System.out.println("=== END DEBUG ===");
            
            System.out.println("=== DEBUG: CURRENT USER ID: " + this.userId + " ===");
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
            try {
                java.sql.Connection ordersConn = con.connectDB();
                java.sql.PreparedStatement ordersPstmt = ordersConn.prepareStatement(ordersSql);
                ordersPstmt.setString(1, this.userId); // Use user ID instead of customer name
                java.sql.ResultSet ordersRs = ordersPstmt.executeQuery();
                
                System.out.println("DEBUG: Executing orders query for user ID: " + this.userId);
                System.out.println("DEBUG: SQL Query: " + ordersSql);
                
                boolean hasOrders = false;
                int orderCount = 0;
                while (ordersRs.next()) {
                    hasOrders = true;
                    orderCount++;
                    String productName = ordersRs.getString("item_name");
                    int qty = ordersRs.getInt("qty");
                    double price = ordersRs.getDouble("price");
                    double total = ordersRs.getDouble("total_amount");
                    String payment = ordersRs.getString("payment_method");
                    String orderDate = ordersRs.getString("sale_date");
                    
                    System.out.println("DEBUG: Found Order #" + orderCount + ": " + productName + " (QTY: " + qty + ", Total: " + total + ")");
                    
                    // Format date
                    String formattedDate = orderDate;
                    try {
                        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
                        SimpleDateFormat outputFormat = new SimpleDateFormat("MMM dd, yyyy");
                        Date date = inputFormat.parse(orderDate);
                        formattedDate = outputFormat.format(date);
                    } catch (Exception e) {
                        formattedDate = orderDate;
                    }
                    
                    model.addRow(new Object[]{
                        productName,
                        qty,
                        String.format("₱%.2f", price),
                        String.format("₱%.2f", total),
                        payment,
                        formattedDate
                    });
                }
                
                System.out.println("DEBUG: Total orders found: " + orderCount);
                
                if (!hasOrders) {
                    model.addRow(new Object[]{"No orders found", "", "", "", "", ""});
                    System.out.println("DEBUG: No orders found for user ID: " + this.userId);
                }
                
                ordersRs.close();
            } catch (Exception e) {
                System.err.println("Error getting orders: " + e.getMessage());
                model.addRow(new Object[]{"Database error", "", "", "", ""});
            }
            
            styleTable();
            
        } catch (Exception e) {
            System.err.println("General error in displayData: " + e.getMessage());
        }
    }
    
    private void styleTable() {
        // Set table styling
        jTable1.setFont(new Font("Arial", Font.PLAIN, 12));
        jTable1.setRowHeight(25);
        jTable1.getTableHeader().setFont(new Font("Arial", Font.BOLD, 12));
        
        // Set column widths
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(300); // Product
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);  // QTY
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100); // Price
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120); // Total
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(120); // Payment
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(150); // Order Date
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myorders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myorders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myorders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myorders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myorders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
