package admin;

import config.config;
import java.io.FileNotFoundException;
import javax.swing.table.DefaultTableModel;
import java.io.PrintWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author PC-001
 */
public class admin_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin_dashboard
     */
 public admin_dashboard() {
   if (!config.isAdminLoggedIn()) {
       config.setAdminSession(0, "Admin");
   }
   initComponents();
    
    // 1. I-setup ang Table Model para sa Checkbox (Column Index 6)
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {
            "User", "Firstname", "Lastname", "Email", "Registered", "Status", "Select"
        }
    ) {
        @Override
        public Class getColumnClass(int columnIndex) {
            if (columnIndex == 6) {
                return Boolean.class; // Para mahimong Checkbox ang ika-pito nga column
            }
            return String.class;
        }
    });

    // 2. I-setup ang Sorter (Kini kinahanglan gawas sa setModel)
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    jTable2.setRowSorter(sorter);

    // 3. I-load ang data gikan sa Database
    updateTableData(); 
}

public void updateTableData() {
    config con = new config();
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); 

    try {
        java.sql.ResultSet rs = con.getData("SELECT * FROM tbl_accounts WHERE status = 'Pending'");
        
        // Kung walay pending, ayaw pag-popup. I-print lang sa console para sa debug.
        if (!rs.isBeforeFirst()) { 
            System.out.println("No pending accounts found."); 
            this.setVisible(true); // Siguruha nga makita gihapon ang dashboard
            return; 
        }

        // Kung naay pending, i-load sa table
        int counter = 1;
        while(rs.next()){
            model.addRow(new Object[]{
                counter++, 
                rs.getString("what_should_we_call_you"), 
                "Casia", 
                rs.getString("email"), 
                rs.getString("date_reg"),
                rs.getString("status"),
                false 
            });
        }
        this.setVisible(true); // I-show ang dashboard kung naay data
    } catch (SQLException ex) {
        System.out.println("Error Loading Table: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("APPROVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 110, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 320, 70));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "User", "Firstname", "Email", "Registered", "Status", "Select"
            }
        ));
        jTable2.setRowHeight(50);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 1030, 480));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL USERS");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER MANAGEMENT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SHOE INVENTORY");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALES LOGS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 480));

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 110, 20));

        txt_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_search.setForeground(new java.awt.Color(102, 102, 102));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 220, 200, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setText("ADMIN DASHBOARD");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 320, 70));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGOUT");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 110, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1300, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
config con = new config();
    int rowCount = jTable2.getRowCount();
    boolean itemSelected = false;

    // 1. Mangutana kung sigurado ba i-approve ang mga gipili
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to approve the selected accounts?", 
            "Approve Confirmation", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // 2. I-loop ang tibuok table
        for (int i = 0; i < rowCount; i++) {
            // I-check ang value sa Column 6 (Select checkbox)
            Object isCheckedObj = jTable2.getValueAt(i, 6);
            Boolean isChecked = (isCheckedObj instanceof Boolean) ? (Boolean) isCheckedObj : false;

            if (isChecked != null && isChecked) {
                // 3. Kuhaon ang email isip primary identifier (Column 3)
                String email = jTable2.getValueAt(i, 3).toString();
                
                // 4. SQL Update statement
                String sql = "UPDATE tbl_accounts SET status = 'Approved' WHERE email = ?";
                
                // 5. I-execute ang update gamit ang imong config class
                con.updateRecord(sql, email); 
                itemSelected = true;
            }
        }

        if (itemSelected) {
            // 6. Refresh ang table data para mawala ang mga na-approve na (kay Pending ra man ang gina-display)
            updateTableData(); 
            JOptionPane.showMessageDialog(this, "Selected accounts have been approved!");
        } else {
            JOptionPane.showMessageDialog(this, "Please select at least one account to approve.");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
      jLabel4.setForeground(java.awt.Color.WHITE);
    jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold

    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
      jLabel4.setForeground(new java.awt.Color(204, 204, 204));
    jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
       jLabel5.setForeground(java.awt.Color.WHITE);
    jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
         jLabel5.setForeground(new java.awt.Color(204, 204, 204));
    jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(java.awt.Color.WHITE);
    jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold

    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
         jLabel6.setForeground(new java.awt.Color(204, 204, 204));
    jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel6MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        config con = new config();
    int rowCount = jTable2.getRowCount();
    boolean itemSelected = false;

    // 1. Mangutana sa Admin kung sigurado ba gyud siya mofuta (Confirmation)
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete the selected accounts?", 
            "Delete Confirmation", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        for (int i = 0; i < rowCount; i++) {
            // I-check kung naka-check ba ang checkbox sa ika-pito nga column (index 6)
            Boolean isChecked = (Boolean) jTable2.getValueAt(i, 6);
            
            if (isChecked != null && isChecked) {
                // Kuhaon ang email (index 3) ising primary key para sa pag-delete
                String email = jTable2.getValueAt(i, 3).toString();
                
                // Saktong SQL para sa pag-delete
                String sql = "DELETE FROM tbl_accounts WHERE email = ?";
                
                con.deleteRecord(sql, email); // Siguruha nga naay deleteRecord method sa imong config
                itemSelected = true;
            }
        }

        if (itemSelected) {
            updateTableData(); // I-refresh ang table aron mawa ang gi-delete
            JOptionPane.showMessageDialog(this, "Selected accounts have been deleted!");
        } else {
            JOptionPane.showMessageDialog(this, "Please select at least one account to delete.");
        }
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
    jTable2.setRowSorter(sorter);
    
    // Kuhaon ang text nga gi-type
    String query = txt_search.getText();
    
    // I-filter ang table base sa gi-type (Case Insensitive)
    // Ang "(?i)" nagpasabot nga dili sensitive sa Big or Small letters
    sorter.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       // 1. Paghimo og instance sa imong totalusers frame
    totalusers usersPage = new totalusers();
    
    // 2. I-center ang frame para nindot tan-awon
    usersPage.setLocationRelativeTo(null);
    
    // 3. I-show ang totalusers frame
    usersPage.setVisible(true);
    
    // 4. I-close o i-hide ang current dashboard (Optional)
    this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       // 1. Paghimo og instance sa imong shoe_inventory frame
    shoe_inventory shoePage = new shoe_inventory();

    // 2. I-center ang frame sa screen para nindot tan-awon
    shoePage.setLocationRelativeTo(null);

    // 3. I-show ang shoe inventory frame
    shoePage.setVisible(true);

    // 4. I-close ang current dashboard para dili mag-double ang windows
    this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            login loginPage = new login();
            loginPage.setLocationRelativeTo(null);
            loginPage.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(shoe_inventory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(java.awt.Color.WHITE);
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        saleslogs sales = new saleslogs(); // Inig "new" nimo ani, mo-run na ang displaySales sa iyang constructor
        sales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            config con = new config();
            try {
                // Inig RUN, mo-check sa database
                java.sql.ResultSet rs = con.getData("SELECT * FROM tbl_accounts WHERE status = 'Pending'");
                
                if (!rs.isBeforeFirst()) {
                    // 1. Popup ra gyud ni mugawas inig RUN (kung walay pending)
                    JOptionPane.showMessageDialog(null, "User Not Found", "Access Denied", JOptionPane.WARNING_MESSAGE);
                    
                    // 2. Inig OK, mo-landing sa LOGIN screen
                    try {
                        Class<?> loginClass = Class.forName("login"); 
                        Object loginInstance = loginClass.getDeclaredConstructor().newInstance();
                        loginClass.getMethod("setLocationRelativeTo", java.awt.Component.class).invoke(loginInstance, (java.awt.Component)null);
                        loginClass.getMethod("setVisible", boolean.class).invoke(loginInstance, true);
                    } catch (Exception e) {
                        System.out.println("Login Redirect Error: " + e.getMessage());
                    }
                } else {
                    // 3. Kung naay pending, mo-lahos sa Dashboard nga walay popup
                    admin_dashboard dash = new admin_dashboard();
                    dash.setVisible(true);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

   
   
}
