/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.config;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author PC-001
 */
public class saleslogs extends javax.swing.JFrame {

    /**
     * Creates new form saleslogs
     */
    public saleslogs() {
    if (!config.isAdminLoggedIn()) {
        try {
            javax.swing.JOptionPane.showMessageDialog(null, "User Not Found", "Access Denied", javax.swing.JOptionPane.WARNING_MESSAGE);
            Class<?> loginClass = Class.forName("login");
            Object loginInstance = loginClass.getDeclaredConstructor().newInstance();
            loginClass.getMethod("setLocationRelativeTo", java.awt.Component.class).invoke(loginInstance, (java.awt.Component)null);
            loginClass.getMethod("setVisible", boolean.class).invoke(loginInstance, true);
        } catch (Exception e) {
            System.out.println("Login Redirect Error: " + e.getMessage());
        }
        dispose();
        return;
    }
    initComponents();
    displaySales(); // Tawgon kini aron mo-load ang data inig abli
}
public void displaySales() {
    config conf = new config();
    String sql = "SELECT item_name AS 'ITEM NAME', "
               + "price AS 'PRICE', "
               + "qty AS 'QTY', "
               + "total_amount AS 'TOTAL' "
               + "FROM tbl_sales";
    
    // Gamita ang jTable1 (ang tinuod nga table component), ayaw ang 'null'
    conf.displayData(sql, jTable1); 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL USERS");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER MANAGEMENT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SHOE INVENTORY");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALES LOGS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 480));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALES LOGS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 990, 480));

        btn_refresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel1.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("ADMIN DASHBOARD");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 320, 70));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGOUT");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, 110, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1300, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1280, 880));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       // 1. Paghimo og instance sa imong totalusers frame
    totalusers usersPage = new totalusers();
    
    // 2. I-center ang frame para nindot tan-awon
    usersPage.setLocationRelativeTo(null);
    
    // 3. I-show ang totalusers frame
    usersPage.setVisible(true);
    
    // 4. I-close o i-hide ang current dashboard (Optional)
    this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(java.awt.Color.WHITE);
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       // 1. Paghimo og instance sa imong admin dashboard
    admin_dashboard dash = new admin_dashboard();
    
    // 2. I-center ang dashboard
    dash.setLocationRelativeTo(null);
    
    // 3. I-pakita ang dashboard
    dash.setVisible(true);
    
    // 4. I-close kining totalusers nga frame
    this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(java.awt.Color.WHITE);
        jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // 1. Paghimo og instance sa imong shoe_inventory frame
        shoe_inventory shoePage = new shoe_inventory();

        // 2. I-center ang frame sa screen para nindot tan-awon
        shoePage.setLocationRelativeTo(null);

        // 3. I-show ang shoe inventory frame
        shoePage.setVisible(true);

        // 4. I-close ang current dashboard para dili mag-double ang windows
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(java.awt.Color.WHITE);
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(java.awt.Color.WHITE);
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel7MouseExited

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
       // Tawgon lang ang method nga atong gihimo kaniadto
    displaySales(); 
   
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            config.clearAdminSession();
            Class<?> loginClass = Class.forName("login");
            Object loginInstance = loginClass.getDeclaredConstructor().newInstance();
            loginClass.getMethod("setLocationRelativeTo", java.awt.Component.class).invoke(loginInstance, (java.awt.Component)null);
            loginClass.getMethod("setVisible", boolean.class).invoke(loginInstance, true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(shoe_inventory.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            config con = new config();
            try {
                // I-check kung naay sulod ang tbl_sales
                java.sql.ResultSet rs = con.getData("SELECT * FROM tbl_sales");
                
                // Kung walay data nga nakit-an
                if (!rs.isBeforeFirst()) { 
                    // 1. I-show ang Popup message
                    javax.swing.JOptionPane.showMessageDialog(null, "User Not Found", "Access Denied", javax.swing.JOptionPane.WARNING_MESSAGE);
                    
                    // 2. Paghimo og instance sa login ug i-pakita
                    try {
                        login loginPage = new login();
                        loginPage.setLocationRelativeTo(null);
                        loginPage.setVisible(true);
                    } catch (Exception e) {
                        System.out.println("Error loading login: " + e.getMessage());
                    }
                } else {
                    // 3. Kung naay data, i-dayon ang pag-abli sa Sales Logs
                    saleslogs sLogs = new saleslogs();
                    sLogs.setLocationRelativeTo(null);
                    sLogs.setVisible(true);
                }
            } catch (java.sql.SQLException e) {
                System.out.println("Database Error: " + e.getMessage());
            }
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
