/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.config;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane; // Import ni para sa alert boxes
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel; 
import static sun.security.jgss.GSSUtil.login;
    
/**
 *
 * @author PC-001
 */
public class totalusers extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public totalusers() {
        if (!config.isAdminLoggedIn()) {
            try {
                Class<?> loginClass = Class.forName("login");
                Object loginInstance = loginClass.getDeclaredConstructor().newInstance();
                loginClass.getMethod("setLocationRelativeTo", java.awt.Component.class).invoke(loginInstance, (java.awt.Component)null);
                loginClass.getMethod("setVisible", boolean.class).invoke(loginInstance, true);
            } catch (Exception e) {
                System.out.println("Login Redirect Error: " + e.getMessage());
            }
            dispose();
            return;
        }
        initComponents();
        displayData(); 
    }

    public void displayData() {
    config con = new config();
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // I-clear ang table sa dili pa i-load

    try {
        // Ang Query: Approved ra ang ipakita
        java.sql.ResultSet rs = con.getData("SELECT * FROM tbl_accounts WHERE status = 'Approved'");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("u_id"), // Siguruha nga husto ang column name sa imong DB
                rs.getString("what_should_we_call_you"), 
                rs.getString("email"), 
                rs.getString("status"), // O bisan unsang column nga gusto nimo ipakita
                rs.getString("date_reg")
            });
        }
    } catch (java.sql.SQLException ex) {
        System.out.println("Error Loading Table: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_username = new javax.swing.JButton();
        txt_id = new javax.swing.JButton();
        txt_status = new javax.swing.JButton();
        txt_status1 = new javax.swing.JButton();
        txt_status2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL USERS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 70));

        jTable1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Status", "Last Login"
            }
        ));
        jTable1.setRowHeight(50);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 1030, 480));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL USERS");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER MANAGEMENT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SHOE INVENTORY");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALES LOGS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 480));

        txt_search.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_search.setForeground(new java.awt.Color(102, 102, 102));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 200, 30));

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, 30));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setText("ADMIN DASHBOARD");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 320, 70));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGOUT");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 110, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1300, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 130));

        txt_username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_username.setText("ADD");
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 110, 30));

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setText("UPDATE");
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 30));

        txt_status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_status.setText("ARCHIVED");
        txt_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_statusActionPerformed(evt);
            }
        });
        jPanel1.add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 100, 30));

        txt_status1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_status1.setText("CLEAR");
        txt_status1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_status1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 100, 30));

        txt_status2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_status2.setText("RESTORE");
        txt_status2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_status2ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(java.awt.Color.WHITE);
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(java.awt.Color.WHITE);
        jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(java.awt.Color.WHITE);
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(java.awt.Color.WHITE);
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18)); // Himoon natong Bold
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18)); // Balik sa Plain
    }//GEN-LAST:event_jLabel7MouseExited

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
      // Siguroha nga jTable1 ang gigamit, dili jTable2
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
    javax.swing.table.TableRowSorter<DefaultTableModel> sorter = new javax.swing.table.TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);

    String query = txt_search.getText();

    // I-filter ang table (Case Insensitive)
    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + query));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // 1. Paghimo og instance sa imong admin dashboard
    admin_dashboard dash = new admin_dashboard();
    
    // 2. I-center ang dashboard
    dash.setLocationRelativeTo(null);
    
    // 3. I-pakita ang dashboard
    dash.setVisible(true);
    
    // 4. I-close kining totalusers nga frame
    this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // 1. Paghimo og instance sa imong shoe_inventory frame
        shoe_inventory shoePage = new shoe_inventory();

        // 2. I-center ang frame sa screen para nindot tan-awon
        shoePage.setLocationRelativeTo(null);

        // 3. I-show ang shoe inventory frame
        shoePage.setVisible(true);

        // 4. I-close ang current dashboard para dili mag-double ang windows
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      // 1. Paghimo og object para sa imong saleslogs frame
    saleslogs sales = new saleslogs();
    
    // 2. I-pakita ang sales logs frame
    sales.setVisible(true);
    
    // 3. I-refresh ang data sa table para naay sulod inig abli
    sales.displaySales();
    
    // 4. I-close o i-hide ang current frame (Admin Dashboard)
    this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   int row = jTable1.getSelectedRow();
    
    // 1. Check if a row is selected
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user from the table to delete!");
        return;
    }

    // 2. Get the Unique ID (Column 0)
    String userId = jTable1.getValueAt(row, 0).toString(); 
    
    // 3. Confirm Deletion in English
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete User ID: " + userId + "?", 
        "Delete Confirmation", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        config con = new config();
        
        // 4. SQL Execution
        // Ensure 'u_id' matches the column name in your SQLite database
        String sql = "DELETE FROM tbl_accounts WHERE u_id = ?";
        con.deleteRecord(sql, userId);
        
        // 5. Refresh and Feedback
        displayData(); // Reloads the table to show updated list
        JOptionPane.showMessageDialog(this, "User deleted successfully!");
    }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // Kinahanglan nimo i-specify ang full name kung naa sa default package
       try {
        // Mogamit ta og Reflection para tawgon ang 'login' class nga naa sa default package
        Class<?> loginClass = Class.forName("login");
        Object loginInstance = loginClass.newInstance();
        
        // I-set ang visibility sa login frame
        java.lang.reflect.Method setVisibleMethod = loginClass.getMethod("setVisible", boolean.class);
        setVisibleMethod.invoke(loginInstance, true);
        
        // I-close ang current frame (totalusers)
        this.dispose();
        
    } catch (Exception ex) {
        // Kung naay error, i-display kini sa console
        System.out.println("Error Redirecting to Login: " + ex.getMessage());
        JOptionPane.showMessageDialog(null, "Cannot find login page. Please check if 'login.java' exists.");
    }


    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
  JTextField nameField = new JTextField(15);
JTextField usernameField = new JTextField(15);
JPasswordField passField = new JPasswordField(15); 

// Dropdown para sa Status
String[] statusOptions = {"Approved", "Pending"};
javax.swing.JComboBox<String> statusCombo = new javax.swing.JComboBox<>(statusOptions);

// Dropdown para sa Role (Admin o User)
String[] roleOptions = {"User", "Admin"};
javax.swing.JComboBox<String> roleCombo = new javax.swing.JComboBox<>(roleOptions);

// 2. Pag-set up sa layout sa Popup (Gihimo nakong 5 rows para sa Role)
javax.swing.JPanel myPanel = new javax.swing.JPanel();
myPanel.setLayout(new java.awt.GridLayout(5, 2, 10, 10)); 

myPanel.add(new javax.swing.JLabel("Name:"));
myPanel.add(nameField);
myPanel.add(new javax.swing.JLabel("Username/Email:"));
myPanel.add(usernameField);
myPanel.add(new javax.swing.JLabel("Password:"));
myPanel.add(passField);
myPanel.add(new javax.swing.JLabel("Status:"));
myPanel.add(statusCombo);
myPanel.add(new javax.swing.JLabel("Account Role:"));
myPanel.add(roleCombo); // Gidugang ang Role dropdown

// 3. I-show ang Popup
int result = JOptionPane.showConfirmDialog(null, myPanel, 
           "Add New User", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

// 4. Inig click sa OK
if (result == JOptionPane.OK_OPTION) {
    String name = nameField.getText().trim();
    String user = usernameField.getText().trim();
    String pass = new String(passField.getPassword());
    String stat = statusCombo.getSelectedItem().toString(); 
    String role = roleCombo.getSelectedItem().toString(); // Kuhaon ang Role
    
    if(name.isEmpty() || user.isEmpty() || pass.isEmpty()){
        JOptionPane.showMessageDialog(null, "Please fill up all fields!");
    } else {
        config con = new config();
        
        // 5. SQL Query: Gidugangan og 'role' nga column
        // Siguruha nga ang imong table naay column named 'role'
        String sql = "INSERT INTO tbl_accounts (what_should_we_call_you, email, password, status, role, date_reg) "
                   + "VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)";
        
        // Pag-insert sa Database (5 na ka parameters)
        con.addRecord(sql, name, user, pass, stat, role);
        
        // Refresh sa Table Display
        displayData(); 
        JOptionPane.showMessageDialog(null, "User Added Successfully!");
    }
    }//GEN-LAST:event_txt_usernameActionPerformed
    }
    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
      // 1. I-check kung naay gi-select nga row sa table
    int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please Choose Table!");
        return;
    }

    // 2. Kuhaon ang data gikan sa table columns
    String id = jTable1.getValueAt(row, 0).toString();
    String currentName = jTable1.getValueAt(row, 1).toString();
    String currentUsername = jTable1.getValueAt(row, 2).toString();
    String currentStatus = jTable1.getValueAt(row, 3).toString();

    // 3. Paghimo sa mga input fields ug i-set ang ilang sulod
    JTextField nameField = new JTextField(currentName, 15);
    JTextField usernameField = new JTextField(currentUsername, 15);
    JTextField statusField = new JTextField(currentStatus, 15);

    // 4. I-set up ang layout sa popup
    javax.swing.JPanel myPanel = new javax.swing.JPanel();
    myPanel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
    myPanel.add(new javax.swing.JLabel("Edit Name:"));
    myPanel.add(nameField);
    myPanel.add(new javax.swing.JLabel("Edit Username/Email:"));
    myPanel.add(usernameField);
    myPanel.add(new javax.swing.JLabel("Edit Status:"));
    myPanel.add(statusField);

    // 5. I-pakita ang Popup
    int result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Update User ID: " + id, JOptionPane.OK_CANCEL_OPTION);

    // 6. Inig click sa OK, i-update ang Database
    if (result == JOptionPane.OK_OPTION) {
        config con = new config();
        String sql = "UPDATE tbl_accounts SET what_should_we_call_you = ?, email = ?, status = ? WHERE u_id = ?";
        
        con.updateRecord(sql, nameField.getText(), usernameField.getText(), statusField.getText(), id);
        
        displayData(); // I-refresh ang table
        JOptionPane.showMessageDialog(null, "Successfully Updated!");
    }

    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_statusActionPerformed
  config con = new config();
    
    // Gi-update nako ang column names base sa imong SQLiteStudio screenshot
    // name -> what_should_we_call_you
    // username -> email (o role, depende unsa imong i-show)
    String sql = "SELECT u_id, what_should_we_call_you, email, status, date_reg FROM tbl_accounts WHERE status = 'Archived'";
    
    con.displayData(sql, jTable1); 
    
    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "The archive is currently empty.");
    } else {
        JOptionPane.showMessageDialog(this, "Archive Table Loaded.");
    }
    }//GEN-LAST:event_txt_statusActionPerformed

    private void txt_status1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_status1ActionPerformed
       int row = jTable1.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user from the table to clear!");
        return;
    }

    String userId = jTable1.getValueAt(row, 0).toString(); // Kuhaon ang ID sa Column 0
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to clear/archive User ID: " + userId + "?", 
        "Clear Confirmation", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        config con = new config();
        // Usbon ang status para matago sa main table
       String sql = "UPDATE tbl_accounts SET status = 'Archived' WHERE u_id = ?";
// GI-TAWAG NIMO DIRI:
con.updateRecord(sql, userId);
        
        displayData(); // I-refresh ang table aron mawala ang archived user
        JOptionPane.showMessageDialog(this, "User cleared and moved to Archive!");
    }

    }//GEN-LAST:event_txt_status1ActionPerformed

    private void txt_status2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_status2ActionPerformed
        int row = jTable1.getSelectedRow();
    
    // 1. Check kung naay napili nga user sa table
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Palihog pagpili una og user sa table nga gusto nimo i-restore!");
        return;
    }

    // 2. Kuhaon ang u_id sa napili nga row (Column 0)
    String userId = jTable1.getValueAt(row, 0).toString(); 
    String userName = jTable1.getValueAt(row, 1).toString(); // what_should_we_call_you
    
    // 3. Confirmation Dialog sa English/Bisaya
    int confirm = JOptionPane.showConfirmDialog(this, 
        "You Want to Restore this User " + userName + " (ID: " + userId + ") Back to Active list?", 
        "Restore Confirmation", 
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        config con = new config();
        
        // 4. I-update ang status gikan sa 'Archived' balik sa 'Approved'
        String sql = "UPDATE tbl_accounts SET status = 'Approved' WHERE u_id = ?";
        con.updateRecord(sql, userId);
        
        // 5. I-refresh ang Archive Table para mawala na ang gi-restore nga user
        String refreshSql = "SELECT u_id, what_should_we_call_you, email, status, date_reg FROM tbl_accounts WHERE status = 'Archived'";
        con.displayData(refreshSql, jTable1); 
        
        JOptionPane.showMessageDialog(this, "User successfully restored!");
    }
    }//GEN-LAST:event_txt_status2ActionPerformed

    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(totalusers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new totalusers().setVisible(true);
            }
        });
  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton txt_id;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton txt_status;
    private javax.swing.JButton txt_status1;
    private javax.swing.JButton txt_status2;
    private javax.swing.JButton txt_username;
    // End of variables declaration//GEN-END:variables

 private void updateTableData() {
    // Kinahanglan lang ni moadto balik sa displayData para i-refresh ang table
    displayData(); 
}

   private void clearFields() {
    txt_id.setText("");
    txt_username.setText("");
    txt_username.setText("");
    txt_status.setText("");
    }
}
